# Generated by Django 5.2.14 on 2026-05-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.FloatField()),
                ('total_distance_miles', models.FloatField()),
                ('total_driving_hours', models.FloatField()),
                ('total_days', models.PositiveIntegerField()),
                ('cycle_after_trip', models.FloatField()),
                ('restart_required', models.BooleanField(default=False)),
                ('trip_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trip Log',
                'verbose_name_plural': 'Trip Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
