# Generated by Django 5.2.14 on 2026-05-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hos_planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="triplog",
            name="current_lat",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="triplog",
            name="current_lon",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="triplog",
            name="dropoff_lat",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="triplog",
            name="dropoff_lon",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="triplog",
            name="pickup_lat",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="triplog",
            name="pickup_lon",
            field=models.FloatField(null=True),
        ),
    ]
